const domainCategories = {
    finance: {
      name: 'Finance & Banking',
      fields: {
        stockSymbol: ['AAPL', 'GOOGL', 'MSFT', 'AMZN', 'FB', 'TSLA', 'NFLX', 'NVDA', 'JPM', 'BAC', 'WMT', 'PG', 'JNJ', 'V', 'MA', 'HD', 'DIS', 'PYPL', 'ADBE', 'CRM', 'INTC', 'CSCO', 'VZ', 'KO', 'PEP'],
        accountType: ['Savings', 'Checking', 'Investment', '401k', 'IRA', 'Money Market', 'Certificate of Deposit', 'Business Checking', 'Student Account', 'Joint Account', 'Trust Account', 'HSA', 'Brokerage', 'Custodial', 'Retirement', 'Credit Card', 'Merchant', 'Foreign Currency', 'High-Yield Savings', 'Zero-Balance'],
        transactionType: ['Deposit', 'Withdrawal', 'Transfer', 'Payment', 'Direct Deposit', 'Wire Transfer', 'ACH', 'Point of Sale', 'ATM', 'Check', 'Bill Pay', 'Recurring', 'International', 'Exchange', 'Credit', 'Debit', 'Refund', 'Reversal', 'Fee', 'Interest'],
        currency: ['USD', 'EUR', 'GBP', 'JPY', 'CHF', 'AUD', 'CAD', 'CNY', 'HKD', 'NZD', 'SGD', 'SEK', 'KRW', 'INR', 'BRL', 'RUB', 'ZAR', 'MXN', 'AED', 'SAR', 'TWD', 'THB', 'TRY'],
        bankingProduct: ['Mortgage', 'Personal Loan', 'Auto Loan', 'Credit Card', 'Student Loan', 'Home Equity', 'Business Loan', 'Line of Credit', 'Overdraft Protection', 'Term Deposit', 'Savings Bond', 'Money Market', 'Retirement Account', 'Investment Account', 'Insurance', 'Safe Deposit Box', 'Foreign Exchange', 'Wire Service', 'Mobile Banking', 'Online Banking'],
        riskLevel: ['Very Low', 'Low', 'Moderate-Low', 'Moderate', 'Moderate-High', 'High', 'Very High', 'Ultra High', 'Conservative', 'Balanced', 'Growth', 'Aggressive', 'Speculative', 'Capital Preservation', 'Income Generation', 'Dynamic', 'Strategic', 'Tactical', 'Alternative', 'Core'],
        financialRatio: ['P/E Ratio', 'EPS', 'ROE', 'ROA', 'Current Ratio', 'Quick Ratio', 'Debt/Equity', 'Gross Margin', 'Operating Margin', 'Net Margin', 'Asset Turnover', 'Inventory Turnover', 'Working Capital', 'Market Cap', 'Beta', 'Alpha', 'Sharpe Ratio', 'Treynor Ratio', 'PEG Ratio', 'Book Value'],
        investmentVehicle: ['Stocks', 'Bonds', 'Mutual Funds', 'ETFs', 'Options', 'Futures', 'Forex', 'Commodities', 'Real Estate', 'Hedge Funds', 'Private Equity', 'Venture Capital', 'Angel Investment', 'P2P Lending', 'Derivatives', 'Index Funds', 'Money Market Funds', 'Treasury Securities', 'Municipal Bonds', 'Corporate Bonds'],
        tradingStrategy: ['Day Trading', 'Swing Trading', 'Position Trading', 'Scalping', 'Momentum Trading', 'Value Investing', 'Growth Investing', 'Dollar Cost Averaging', 'Buy and Hold', 'Market Timing', 'Arbitrage', 'Pair Trading', 'Mean Reversion', 'Trend Following', 'Range Trading', 'News Trading', 'Grid Trading', 'Martingale', 'Hedging', 'Portfolio Rebalancing'],
        regulatoryCompliance: ['SEC', 'FINRA', 'Basel III', 'Dodd-Frank', 'GDPR', 'KYC', 'AML', 'SOX', 'PSD2', 'MiFID II', 'FATCA', 'CRS', 'IFRS', 'GAAP', 'Federal Reserve', 'CECL', 'Bank Secrecy Act', 'Volcker Rule', 'EMIR', 'Consumer Protection'],
        financialSoftware: ['QuickBooks', 'SAP', 'Oracle', 'Sage', 'Bloomberg', 'Reuters Eikon', 'FactSet', 'Capital IQ', 'Morningstar', 'MetaTrader', 'Interactive Brokers', 'Fidelity Active Trader Pro', 'TD Ameritrade thinkorswim', 'E*TRADE Pro', 'Charles Schwab StreetSmart Edge', 'Robinhood', 'Webull', 'TradeStation', 'NinjaTrader', 'MultiCharts'],
        marketIndex: ['S&P 500', 'Dow Jones', 'NASDAQ', 'Russell 2000', 'FTSE 100', 'DAX', 'Nikkei 225', 'Hang Seng', 'ASX 200', 'CAC 40', 'KOSPI', 'BSE Sensex', 'Bovespa', 'TSX', 'Euro Stoxx 50', 'MSCI World', 'MSCI Emerging Markets', 'FTSE All-World', 'Bloomberg Commodity', 'VIX'],
        financialCertification: ['CFA', 'CFP', 'CPA', 'FRM', 'CAIA', 'Series 7', 'Series 63', 'Series 65', 'Series 66', 'ChFC', 'CLU', 'CPWA', 'CIMA', 'EA', 'ACCA', 'CIA', 'CMA', 'CBV', 'ASA', 'PFS'],
        taxCategory: ['Income Tax', 'Capital Gains Tax', 'Property Tax', 'Sales Tax', 'VAT', 'Estate Tax', 'Gift Tax', 'Corporate Tax', 'Dividend Tax', 'Self-Employment Tax', 'Payroll Tax', 'Excise Tax', 'Alternative Minimum Tax', 'Foreign Tax', 'State Tax', 'Local Tax', 'Luxury Tax', 'Sin Tax', 'Carbon Tax', 'Wealth Tax'],
        creditRating: ['AAA', 'AA+', 'AA', 'AA-', 'A+', 'A', 'A-', 'BBB+', 'BBB', 'BBB-', 'BB+', 'BB', 'BB-', 'B+', 'B', 'B-', 'CCC+', 'CCC', 'CCC-', 'D']
      }
    },
    
    investmentBanking: {
      name: 'Investment Banking',
      fields: {
        dealType: ['M&A', 'IPO', 'Private Placement', 'Debt Offering', 'Restructuring', 'Leveraged Buyout', 'SPAC', 'Secondary Offering', 'Rights Issue', 'Bond Offering', 'Syndicated Loan', 'Asset Sale', 'Spin-Off', 'Joint Venture', 'Strategic Advisory', 'Divestiture', 'Recapitalization', 'Debt Restructuring', 'Direct Listing', 'Cross-Border Transaction'],
        valuationMethod: ['DCF', 'Comparable Company', 'Precedent Transactions', 'LBO', 'Asset-Based', 'Option Pricing', 'Sum-of-Parts', 'First Chicago', 'Venture Capital', 'Rule of Thumb', 'Market Multiples', 'Replacement Cost', 'NAV', 'Gordon Growth', 'FCF Yield', 'PEG Analysis', 'EVA', 'Real Options', 'Monte Carlo', 'Industry-Specific'],
        dueFiligence: ['Financial', 'Legal', 'Tax', 'Commercial', 'Technical', 'Environmental', 'HR', 'IT', 'Operational', 'Market', 'Strategic', 'Regulatory', 'Insurance', 'Intellectual Property', 'Real Estate', 'Customer', 'Supplier', 'Management', 'Compliance', 'Cultural'],
        pitchbookSection: ['Executive Summary', 'Investment Thesis', 'Market Analysis', 'Financial Analysis', 'Valuation', 'Transaction Comparables', 'Trading Comparables', 'Strategic Rationale', 'Risk Factors', 'Management Team', 'Industry Overview', 'Growth Strategy', 'Competitive Analysis', 'Operating Model', 'Synergies Analysis', 'Capital Structure', 'Sources and Uses', 'Financial Projections', 'Transaction Timeline', 'Next Steps'],
        advisoryService: ['M&A Advisory', 'Capital Raising', 'Restructuring', 'Strategic Advisory', 'Fairness Opinion', 'Valuation Services', 'Transaction Support', 'Due Diligence', 'Integration Planning', 'Board Advisory', 'Crisis Management', 'Succession Planning', 'Risk Advisory', 'Portfolio Review', 'Market Entry', 'Partner Search', 'Tender Offer', 'Privatization', 'Hostile Defense', 'Activism Defense'],
        financialModeling: ['Three Statement', 'DCF', 'LBO', 'M&A', 'IPO', 'Restructuring', 'Working Capital', 'Debt Schedule', 'Operating Model', 'Consolidation', 'Sensitivity Analysis', 'Scenario Analysis', 'Sum-of-Parts', 'Monte Carlo', 'Option Pricing', 'Project Finance', 'Real Estate', 'Mining', 'Oil & Gas', 'Start-up'],
        industryGroup: ['Technology', 'Healthcare', 'Consumer', 'Industrial', 'Energy', 'Financial Institutions', 'Real Estate', 'Media', 'Telecommunications', 'Natural Resources', 'Infrastructure', 'Agriculture', 'Transportation', 'Retail', 'Education', 'Aerospace', 'Defense', 'Gaming', 'Hospitality', 'Environmental'],
        dealStructure: ['Stock Purchase', 'Asset Purchase', 'Merger', 'Reverse Merger', 'Forward Merger', 'Carve-Out', 'Spin-Off', 'Split-Off', 'Joint Venture', 'Strategic Alliance', 'Licensing Agreement', 'Franchise Agreement', 'Distribution Agreement', 'Manufacturing Agreement', 'Service Agreement', 'Technology Transfer', 'IP Transfer', 'Employee Transfer', 'Real Estate Transfer', 'Equipment Transfer'],
        marketCondition: ['Bull Market', 'Bear Market', 'Sideways Market', 'Volatile Market', 'Recovery', 'Recession', 'Depression', 'Expansion', 'Peak', 'Trough', 'Stagflation', 'Hyperinflation', 'Deflation', 'Crisis', 'Boom', 'Bust', 'Correction', 'Rally', 'Consolidation', 'Breakout'],
        stakeholder: ['Shareholders', 'Board of Directors', 'Management', 'Employees', 'Customers', 'Suppliers', 'Creditors', 'Regulators', 'Government', 'Community', 'Media', 'Analysts', 'Investors', 'Partners', 'Competitors', 'Industry Groups', 'Labor Unions', 'Environmental Groups', 'Social Groups', 'Political Groups'],
        exitStrategy: ['IPO', 'Strategic Sale', 'Financial Sale', 'Management Buyout', 'Employee Buyout', 'Family Succession', 'Liquidation', 'Recapitalization', 'Secondary Sale', 'Dual-Track', 'Spin-Off', 'Split-Off', 'Carve-Out', 'Asset Sale', 'Stock Sale', 'Merger', 'Reverse Merger', 'SPAC', 'Direct Listing', 'Auction'],
        dealTeam: ['Managing Director', 'Director', 'Vice President', 'Associate', 'Analyst', 'Industry Expert', 'Product Specialist', 'Legal Counsel', 'Accountant', 'Tax Advisor', 'Environmental Consultant', 'Technical Consultant', 'HR Consultant', 'IT Consultant', 'Operations Consultant', 'Strategy Consultant', 'Marketing Consultant', 'Financial Consultant', 'Risk Consultant', 'Integration Consultant'],
        synergies: ['Revenue Enhancement', 'Cost Reduction', 'Operating Efficiency', 'Market Expansion', 'Product Development', 'Technology Integration', 'Supply Chain', 'Distribution Network', 'Customer Base', 'Talent Acquisition', 'Brand Value', 'Intellectual Property', 'Geographic Expansion', 'Vertical Integration', 'Horizontal Integration', 'Tax Benefits', 'Capital Structure', 'Working Capital', 'Asset Utilization', 'Risk Reduction'],
        riskFactor: ['Market Risk', 'Credit Risk', 'Operational Risk', 'Liquidity Risk', 'Legal Risk', 'Regulatory Risk', 'Reputational Risk', 'Strategic Risk', 'Technology Risk', 'Environmental Risk', 'Political Risk', 'Economic Risk', 'Social Risk', 'Competition Risk', 'Integration Risk', 'Execution Risk', 'Financial Risk', 'Tax Risk', 'Currency Risk', 'Interest Rate Risk'],
        dealDocument: ['Teaser', 'CIM', 'Management Presentation', 'Financial Model', 'Due Diligence Report', 'Valuation Analysis', 'LOI', 'Term Sheet', 'Purchase Agreement', 'Shareholders Agreement', 'Employment Agreement', 'Non-Compete Agreement', 'Confidentiality Agreement', 'Disclosure Schedule', 'Legal Opinion', 'Tax Opinion', 'Fairness Opinion', 'Board Resolution', 'Proxy Statement', 'SEC Filings']
      }
    }}